### ISSUE TITLE
Deprecated selector in `vim-mode-plus-exchange/styles/vim-mode-plus-exchange.less`

### ISSUE THREAD

**Issue by liam-ngy** [dillonkearns/atom-vim-mode-plus-exchange#1]
In `vim-mode-plus-exchange/styles/vim-mode-plus-exchange.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor.exchange-pending .vim-mode-plus-persistent-selection .region,
atom-text-editor.exchange-pending::shadow .vim-mode-plus-persistent-selection .region` => `atom-text-editor.exchange-pending .vim-mode-plus-persistent-selection .region,
atom-text-editor.exchange-pending.editor .vim-mode-plus-persistent-selection .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by dillonkearns** [comment]
Thanks for reporting the issue @hnguyen94!
